# mypy: ignore-errors
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\x14phoenix.inference.v1\"%\n\x12HealthCheckRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"\x9a\x01\n\x13HealthCheckResponse\x12G\n\x06status\x18\x01 \x01(\x0e\x32\x37.phoenix.inference.v1.HealthCheckResponse.ServingStatus\":\n\rServingStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\"^\n\x0ePredictRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x15\n\rmodel_version\x18\x02 \x01(\t\x12\x11\n\tentity_id\x18\x03 \x01(\t\x12\x10\n\x08\x66\x65\x61tures\x18\x04 \x03(\x02\"\x83\x01\n\x0fPredictResponse\x12\x15\n\rprediction_id\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x0e\n\x06result\x18\x04 \x03(\x02\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12\x12\n\nlatency_ms\x18\x06 \x01(\x02\x32\xce\x01\n\x10InferenceService\x12V\n\x07Predict\x12$.phoenix.inference.v1.PredictRequest\x1a%.phoenix.inference.v1.PredictResponse\x12\x62\n\x0bHealthCheck\x12(.phoenix.inference.v1.HealthCheckRequest\x1a).phoenix.inference.v1.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHCHECKREQUEST']._serialized_start=41
  _globals['_HEALTHCHECKREQUEST']._serialized_end=78
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=81
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=235
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_start=177
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_end=235
  _globals['_PREDICTREQUEST']._serialized_start=237
  _globals['_PREDICTREQUEST']._serialized_end=331
  _globals['_PREDICTRESPONSE']._serialized_start=334
  _globals['_PREDICTRESPONSE']._serialized_end=465
  _globals['_INFERENCESERVICE']._serialized_start=468
  _globals['_INFERENCESERVICE']._serialized_end=674
# @@protoc_insertion_point(module_scope)
