apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | default "" | b64enc | quote }}
  REDIS_URL: {{ .Values.secrets.redisUrl | default "" | b64enc | quote }}
  KAFKA_URL: {{ .Values.secrets.kafkaUrl | default "" | b64enc | quote }}
  MLFLOW_TRACKING_URI: {{ .Values.secrets.mlflowTrackingUri | default "" | b64enc | quote }}
